# Generated by Django 5.2.5 on 2025-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='originals/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
    ]
